# Generated by Django 4.0.5 on 2022-06-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_leader',
            field=models.IntegerField(blank=True),
        ),
    ]
