# Generated by Django 4.0.5 on 2022-06-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_leader',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
