# Generated by Django 4.0.5 on 2022-06-04 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_id_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='employee.job_position'),
        ),
    ]
