# Generated by Django 4.0.5 on 2022-06-04 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.job_position'),
        ),
    ]
