# Generated by Django 4.0.5 on 2022-06-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
