# Generated by Django 4.0.5 on 2022-06-05 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_rename_name_employee_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.job_position'),
        ),
    ]
